[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/mengyulin/1102_CompThinking/blob/main/Adventure31/冒險31_Array大變身.ipynb)

# 冒險 31 Array 大變身

In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

用亂數取一個 array，總共有100個數字，從標準常態分配取出來。

In [2]:
A = np.random.randn(100)

In [3]:
A

array([ 0.69359336,  0.11305031, -1.93221183,  1.29800247,  0.31327852,
       -0.13816531, -0.39355926,  1.58558961, -1.78639605, -1.10301877,
       -0.16543018,  0.54081963, -1.32760047, -0.90151741, -0.08198245,
       -0.55999712, -0.16343142,  0.17719847, -0.14744352,  0.8885209 ,
       -0.52669908,  0.93730192,  0.29578118,  1.25291345, -0.32083925,
       -0.40515445, -1.62454424, -1.17191737, -1.07139887,  1.54609062,
        1.45057122,  0.98228719, -2.06318169,  0.595482  , -1.24198923,
        0.79039743, -1.0840031 , -0.96218532,  0.99765123,  1.13185248,
        0.22557229, -1.49576327,  0.15967322,  0.57673384,  0.11186036,
        1.1423319 , -1.66333806, -1.31939861, -2.16519752, -0.78654888,
        0.51345074, -1.30724882, -1.43706441,  3.28555986,  1.05542224,
       -0.87960985,  0.46985148, -0.5748012 ,  0.5299661 , -1.63736643,
       -0.18966149, -0.13594098,  0.88795421, -0.56171306,  0.29663201,
       -1.67186582, -1.4900226 ,  0.42538798, -1.05549816, -1.65

A 目前的形狀。

In [4]:
A.shape

(100,)

把 A 變成 5$\times$20 的矩陣。

In [5]:
A.shape = (5, 20)

In [6]:
A

array([[ 0.69359336,  0.11305031, -1.93221183,  1.29800247,  0.31327852,
        -0.13816531, -0.39355926,  1.58558961, -1.78639605, -1.10301877,
        -0.16543018,  0.54081963, -1.32760047, -0.90151741, -0.08198245,
        -0.55999712, -0.16343142,  0.17719847, -0.14744352,  0.8885209 ],
       [-0.52669908,  0.93730192,  0.29578118,  1.25291345, -0.32083925,
        -0.40515445, -1.62454424, -1.17191737, -1.07139887,  1.54609062,
         1.45057122,  0.98228719, -2.06318169,  0.595482  , -1.24198923,
         0.79039743, -1.0840031 , -0.96218532,  0.99765123,  1.13185248],
       [ 0.22557229, -1.49576327,  0.15967322,  0.57673384,  0.11186036,
         1.1423319 , -1.66333806, -1.31939861, -2.16519752, -0.78654888,
         0.51345074, -1.30724882, -1.43706441,  3.28555986,  1.05542224,
        -0.87960985,  0.46985148, -0.5748012 ,  0.5299661 , -1.63736643],
       [-0.18966149, -0.13594098,  0.88795421, -0.56171306,  0.29663201,
        -1.67186582, -1.4900226 ,  0.42538798, -

若要讀取 A 在不同維度的元素個數，也可以用 `shape` 指令。A 的第一、第二個維度之元素個數分別為

In [7]:
A.shape[0]

5

In [8]:
A.shape[1]

20

要改變array的形狀還可以這樣，這次我們想換成100$\times$1的矩陣。

In [9]:
A.reshape(100, 1)

array([[ 0.69359336],
       [ 0.11305031],
       [-1.93221183],
       [ 1.29800247],
       [ 0.31327852],
       [-0.13816531],
       [-0.39355926],
       [ 1.58558961],
       [-1.78639605],
       [-1.10301877],
       [-0.16543018],
       [ 0.54081963],
       [-1.32760047],
       [-0.90151741],
       [-0.08198245],
       [-0.55999712],
       [-0.16343142],
       [ 0.17719847],
       [-0.14744352],
       [ 0.8885209 ],
       [-0.52669908],
       [ 0.93730192],
       [ 0.29578118],
       [ 1.25291345],
       [-0.32083925],
       [-0.40515445],
       [-1.62454424],
       [-1.17191737],
       [-1.07139887],
       [ 1.54609062],
       [ 1.45057122],
       [ 0.98228719],
       [-2.06318169],
       [ 0.595482  ],
       [-1.24198923],
       [ 0.79039743],
       [-1.0840031 ],
       [-0.96218532],
       [ 0.99765123],
       [ 1.13185248],
       [ 0.22557229],
       [-1.49576327],
       [ 0.15967322],
       [ 0.57673384],
       [ 0.11186036],
       [ 1

若一個 array 的形狀是 (100,), 代表是一個一維的向量，裡面有 100 個數字。

若 array 的形狀是 (100,1)，則代表是一個二維矩陣，總共有 100 個列，每一列有 100 個數字。

reshape 後形狀沒有改變。

In [8]:
A.shape

(5, 20)

賦值才能改變形狀。

In [10]:
A = A.reshape(100, 1)
A.shape

(100, 1)