# 冒險 35 練習

某大學中文系希望錄取文科成績好的學生。請使用冒險 34 的 array 快篩法，從 grades.csv 的學測成績資料中找出國文、英文及社會科成績都超過 13 級分的學生姓名。

In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
df = pd.read_csv('grades.csv') 

In [5]:
df.head()

姓名  國文  英文  數學  自然  社會
0  劉俊安   9  10  15  10  13
1  胡玉華  10  10  10   8   9
2  黃淑婷  13  15   8  11  14
3  陳上紫  10  10   8   9  14
4  崔靜成  13  12  14  12  13

In [6]:
name = df.姓名.values

In [7]:
name

array(['劉俊安', '胡玉華', '黃淑婷', '陳上紫', '崔靜成', '張雅岳', '梁俊翔', '林金鳳', '許協旺',
       '郭雅惠', '張志偉', '周皇樺', '李正偉', '黃旭忠', '葉雅琳', '黃淑慧', '吳芝菁', '聶珮君',
       '梁慧君', '葉曉玲', '陳智超', '黃奕霞', '沈昆純', '許惠雯', '陳竹伯', '蔡亦瑄', '戴喜寶',
       '馮白屏', '王金鳳', '闕進綠', '連瑋玲', '林秀娟', '林建亨', '王佳蓉', '曾淑玟', '盧冠宏',
       '詹威德', '曾怡君', '吳文伯', '段冠廷', '吳欣強', '曲秀芬', '趙恭群', '林士茜', '童心怡',
       '謝亮夫', '柳菁蘭', '葉子豪', '陳怡婷', '朱寶原', '馮伶瑋', '劉彥斌', '黃慧綸', '駱穎琦',
       '陳怡潔', '林意珍', '陳亭妏', '胡淳茜', '陳允凌', '芮秋辛', '曾昇喬', '周筠菁', '許立偉',
       '張山琇', '俞志峰', '謝雅琳', '邱盈俊', '林哲法', '劉麗芬', '蔣奕任', '葉儀依', '葉必盈',
       '陳欣玲', '吳志遠', '劉雅友', '宋美珠', '周育霖', '黃介喬', '葉孟名', '宣宣士', '施雅鈴',
       '楊彥伶', '蕭呈萍', '李士賢', '胡凱琳', '張雅彬', '林貞儀', '趙偉希', '戴青英', '郭順誠',
       '胡勝傑', '陳登翰', '蔡淑孝', '李曼夢', '林與忠', '蔡佳燕', '吳筱婷', '陳家銘', '李明威',
       '農揚勇'], dtype=object)

In [8]:
ch = df.國文.values
ch

array([ 9, 10, 13, 10, 13, 13, 11,  8,  9, 10, 14, 13, 11, 15,  8, 11, 14,
       12,  9, 14, 13,  9, 12, 10, 10, 13, 13,  8, 15, 14,  8, 15,  9, 14,
       13, 14, 12, 11,  8,  9, 12, 14, 14, 12, 13,  9, 14,  8, 15, 10, 12,
       14, 12, 14, 15,  9, 11, 12, 10, 11, 14, 14,  8, 12,  9, 13, 10, 14,
        8, 12,  9,  9, 10, 13, 14, 13,  9, 13, 12,  9, 13, 11, 11, 10, 10,
       10, 11, 10, 11, 13,  8, 14,  8, 11, 10,  9,  8, 14, 15,  9])

In [9]:
eng = df.英文.values
eng

array([10, 10, 15, 10, 12, 12, 13,  9,  9, 15,  9,  9, 15, 14, 13,  8,  9,
       11,  8,  9,  9,  8, 14, 13, 12, 13, 11, 13, 14, 11, 10, 12, 11, 15,
       12, 11, 13, 12,  8,  8, 13, 14, 12, 15, 13,  8, 12,  9, 14, 14, 12,
       11,  9, 10, 15, 15, 14, 15, 13, 10, 12,  8, 10, 11, 14, 14, 14,  9,
       14, 12, 13,  8,  9, 15,  9,  8, 12, 10, 13, 10, 15,  8, 14, 14,  8,
       11, 10, 13,  8, 13, 11, 11, 12,  9,  9, 10, 10,  9,  9, 11])

In [10]:
soc = df.社會.values
soc

array([13,  9, 14, 14, 13,  8, 14,  8, 10,  9, 12, 15, 15, 10, 14, 15,  9,
        9, 12,  9, 13,  8,  9, 10, 14, 12,  9, 10,  8, 11, 13, 15, 11,  8,
        9, 11, 14, 14, 12, 15,  9, 15, 15, 13, 13,  9, 14, 15, 15, 15, 11,
       13,  9, 15, 11,  9, 10, 11, 14,  8, 15, 12,  9, 15, 15,  9,  8, 14,
       14,  8, 14, 12, 10,  8, 11, 11, 12, 13, 11, 13, 13, 15,  9, 13, 15,
        8, 13, 15, 10,  9, 15, 12, 11,  8, 15, 14, 15, 12, 15, 10])

In [11]:
ch > 13

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True, False, False,  True, False,
       False,  True, False, False, False, False, False, False, False,
       False,  True,  True, False,  True, False,  True, False,  True,
       False, False, False, False, False,  True,  True, False, False,
       False,  True, False,  True, False, False,  True, False,  True,
        True, False, False, False, False, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False,  True,  True,
       False])

In [12]:
eng > 13

array([False, False,  True, False, False, False, False, False, False,
        True, False, False,  True,  True, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False, False, False, False,  True, False,  True, False,
       False, False, False,  True,  True, False, False, False, False,
        True,  True,  True,  True, False, False, False, False, False,
       False,  True,  True,  True, False,  True, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [13]:
soc > 13

array([False, False,  True,  True, False, False,  True, False, False,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
        True,  True, False,  True, False,  True,  True, False, False,
       False,  True,  True,  True,  True, False, False, False,  True,
       False, False, False, False,  True, False,  True, False, False,
        True,  True, False, False,  True,  True, False,  True, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False, False,  True,  True,  True, False,  True,
       False])

In [15]:
name[(ch > 13) & (eng > 13) & (soc > 13)]

array(['曲秀芬', '陳怡婷'], dtype=object)