[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/mengyulin/1102_CompThinking/blob/main/Adventure32/冒險32_Array快速生成法.ipynb)

# 冒險 32 Array 快速生成法

In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

生成 array 的標準方法。

先生成一個 list。

In [2]:
xy = [[x, y] for x in range(5) for y in range(3)]

In [5]:
xy

[[0, 0],
 [0, 1],
 [0, 2],
 [1, 0],
 [1, 1],
 [1, 2],
 [2, 0],
 [2, 1],
 [2, 2],
 [3, 0],
 [3, 1],
 [3, 2],
 [4, 0],
 [4, 1],
 [4, 2]]

用 array 包起來。

In [7]:
xy = np.array(xy)
xy

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2],
       [3, 0],
       [3, 1],
       [3, 2],
       [4, 0],
       [4, 1],
       [4, 2]])

生成特殊的 array。

零向量

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

零矩陣

In [9]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((3,5))   # 產生壹向量或壹矩陣

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

單位矩陣

In [15]:
np.eye(5)  # 數學的單位矩陣，符號： I  

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])