[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/mengyulin/1102_CompThinking/blob/main/Adventure30/冒險30練習.ipynb)

# 冒險 30 練習


三位同學的成績分別為

| 出席 (5%) | 平時成績 (20%) | 期中考 (35%) | 期末考 (40%) |
|--------|-------------|--------------|--------------|
| 100    | 85          | 70           | 80           |
| 30     | 12          | 88           | 77           |
| 50     | 85          | 91           | 33           |

## 問題一 (10 分)

請使用陣列與內積，計算學期總成績之後，再做調整。調整公式為原始總成績乘上 1.1 倍後，再加上 2 分。

## 問題二 (10 分）

前面的成果應該會出現大於 100 分的總成績。請寫一個 for 迴圈，檢查若最終總成績大於 100 分則調整為 100 分。


In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

In [2]:
grades = np.array([[100, 95, 96, 98],
                 [30, 12, 88, 77],
                 [50, 85, 91, 33]])

grades

array([[100,  95,  96,  98],
       [ 30,  12,  88,  77],
       [ 50,  85,  91,  33]])

In [3]:
weights = np.array([0.05, 0.2, 0.35, 0.4])
weights

array([0.05, 0.2 , 0.35, 0.4 ])

檢查 weights 是否總和為 1:

In [4]:
weights.sum()

1.0

In [5]:
final = grades @ weights
final

array([96.8 , 65.5 , 64.55])

In [6]:
finalmod = final * 1.1 + 2
finalmod

array([108.48 ,  74.05 ,  73.005])

修正超過 100 分之成績：

In [7]:
for i in range(grades.shape[0]):
    if finalmod[i] >= 100:
        finalmod[i] = 100
finalmod

array([100.   ,  74.05 ,  73.005])